

(defun opcDistancia()
   (terpri)
   (princ "Distancia:")
   (terpri)
   (princ "Ingresa la velocidad (mts/s): ")
   (setq velocidad (read))
   (princ "Ingresa el tiempo (s): ")
   (setq tiempo (read))
   (setq distancia (* velocidad tiempo))
   (terpri)
   (princ "La distancia es: ")
   (write distancia)
   (write "metros")
   (main)
)


(defun opcTiempo()
   (terpri)
   (princ "Tiempo:")
   (terpri)
   (princ "Ingresa la distancia (mts): ")
   (setq distancia (read))
   (princ "Ingresa la velocidad (mts/s): ")
   (setq velocidad (read))
   (setq tiempo (/ distancia velocidad))
   (terpri)
   (princ "El tiempo es: ")
   (write tiempo)
   (write "segundos")
   (main)
)


(defun opcVelocidad()
   (terpri)
   (princ "Velocidad:")
   (terpri)
   (princ "Ingresa la distancia (mts): ")
   (setq distancia (read))
   (princ "Ingresa el tiempo (s): ")
   (setq tiempo (read))
   (setq velocidad (/ distancia tiempo))
   (terpri)
   (princ "La velocidad es: ")
   (write velocidad)
   (write "mts/s")
   (main)
)

(defun main()
   (terpri)
   (princ "Selecciona una de las siguientes opciones para continuar...")
   (terpri)
   (princ "1.- Distancia")
   (terpri)
   (princ "2.- Tiempo")
   (terpri)
   (princ "3.- Velocidad")
   (terpri)
   (setq opc (read))
   (terpri)
   (if (= opc 1)
   	(opcDistancia))
   (if (= opc 2)
   	(opcTiempo))
   (if (= opc 3)
   	(opcVelocidad))
)
(main)

